template: Hello, %s!

defaultName: ${DW_DEFAULT_NAME:-Stranger}

# Database settings
database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:test_mem
  properties:
    charSet: UTF-8
    hibernate.hbm2ddl.auto: create

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

# the key needs to match the configuration key of the renderer (ViewRenderer::getConfigurationKey)
viewRendererConfiguration:
    freemarker:
        strict_syntax: yes
        whitespace_stripping: yes